#!/bin/bash

### BEGIN INIT INFO
# Provides:          sourtasker
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start sourtasker
# Description:       Start the Soucerer Task Worker Process.
### END INIT INFO

case "$1" in
  start)
        cd ~summaggle/summaggle_sourcerer
        if [ -f /var/run/sourtasker.pid ]
        then
                PID=`cat /var/run/sourcerver.pid`
                kill  $PID
                while [[ ( -d /proc/$PID ) && ( -z `grep zombie /proc/$PID/status` ) ]]; do
                   sleep 1
                done
                rm /var/run/sourtasker.pid
        fi
        ./sourtasker.sh
        ;;
  stop)
        cd ~summaggle/summaggle_sourcerer
        if [ -f /var/run/sourtasker.pid ]
        then
                PID=`cat /var/run/sourtasker.pid`
                kill  $PID
                while [[ ( -d /proc/$PID ) && ( -z `grep zombie /proc/$PID/status` ) ]]; do
                   sleep 1
                done
                rm /var/run/sourtasker.pid
        fi
        ;;
  restart|force-reload)
        cd ~summaggle/summaggle_sourcerer
        if [ -f /var/run/sourtasker.pid ]
        then
                PID=`cat /var/run/sourtasker.pid`
                kill  $PID
                while [[ ( -d /proc/$PID ) && ( -z `grep zombie /proc/$PID/status` ) ]]; do
                   sleep 1
                done
                rm /var/run/sourtasker.pid
        fi
        ./sourtasker.sh
        ;;
  *)
        echo "Usage: /etc/init.d/sourtasker {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
